#pragma once
#include <winrt/Windows.Foundation.h>
#include <winrt/Windows.Foundation.Collections.h>
#include "winrt/Windows.Web.Http.h"
#include <iostream>
#include <winrt/Windows.Data.Json.h>
#include <chrono>
#include <thread>
#include <fcntl.h>
#include <io.h>
